OK_FORMAT = True

test = {   'name': 'q1',
    'points': None,
    'suites': [   {   'cases': [   {   'code': '>>> def test_vae():\n'
                                               '...     torch.manual_seed(0)\n'
                                               '...     torch.cuda.manual_seed_all(0)\n'
                                               '...     torch.backends.cudnn.deterministic = True\n'
                                               '...     torch.backends.cudnn.benchmark = False\n'
                                               '>>> \n'
                                               '...     vae_test = VAE(image_size=4, z_dim=2)\n'
                                               '...     x_test = torch.rand((8, 4))\n'
                                               '...     mu_test = torch.rand((8, 2))\n'
                                               '...     log_var_test = torch.rand((8, 2))\n'
                                               '>>> \n'
                                               '...     rp_output = vae_test.reparameterize(mu_test, log_var_test)\n'
                                               '...     rp_gt = torch.tensor([[ 0.6529, -0.2069],\n'
                                               '...             [-1.8231, -0.0500],\n'
                                               '...             [ 0.1616, -0.2011],\n'
                                               '...             [ 0.9458, -0.1417],\n'
                                               '...             [ 1.3442, -0.1257],\n'
                                               '...             [ 0.1344,  1.3360],\n'
                                               '...             [-0.4715,  2.4905],\n'
                                               '...             [ 1.5514, -0.5676]])\n'
                                               '...     assert torch.allclose(rp_output, rp_gt, rtol=0.01)\n'
                                               '>>> \n'
                                               '...     forward_output0, forward_output1, forward_output2 = vae_test.forward(x_test)\n'
                                               '...     forward_gt0 = torch.tensor([[0.4729, 0.5803, 0.5890, 0.4816],\n'
                                               '...             [0.5211, 0.4682, 0.6075, 0.4646],\n'
                                               '...             [0.5068, 0.5121, 0.6547, 0.4849],\n'
                                               '...             [0.4263, 0.4687, 0.4712, 0.5015],\n'
                                               '...             [0.4628, 0.5213, 0.5361, 0.4744],\n'
                                               '...             [0.4729, 0.5737, 0.6195, 0.4845],\n'
                                               '...             [0.5124, 0.5056, 0.6423, 0.4812],\n'
                                               '...             [0.4404, 0.4757, 0.4941, 0.4939]])\n'
                                               '...     forward_gt1 = torch.tensor([[-0.0652, -0.3491],\n'
                                               '...             [-0.0713, -0.2738],\n'
                                               '...             [-0.0366, -0.2864],\n'
                                               '...             [-0.1351, -0.3794],\n'
                                               '...             [-0.0989, -0.4459],\n'
                                               '...             [-0.1657, -0.4463],\n'
                                               '...             [-0.1255, -0.3906],\n'
                                               '...             [-0.0388, -0.3843]])\n'
                                               '...     forward_gt2 = torch.tensor([[-0.1562, -0.1711],\n'
                                               '...             [-0.2215, -0.1416],\n'
                                               '...             [-0.2304, -0.0908],\n'
                                               '...             [-0.3226, -0.1318],\n'
                                               '...             [-0.2441, -0.2435],\n'
                                               '...             [-0.2406, -0.2178],\n'
                                               '...             [-0.2838, -0.2298],\n'
                                               '...             [-0.2731, -0.1792]])\n'
                                               '...     assert torch.allclose(forward_output0, forward_gt0, rtol=0.01)\n'
                                               '...     assert torch.allclose(forward_output1, forward_gt1, rtol=0.01)\n'
                                               '...     assert torch.allclose(forward_output2, forward_gt2, rtol=0.01)\n'
                                               '>>> test_vae()\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
